import { ops, op_by_mn } from "./ops.js";
import { chunk, eb2code } from "./utils.js";
import { to_nibs, disp_to_nibs, byte_from, fw_to_bytes } from "./bytes.js";
import { ops_extended } from "./ops_extended.js";

export const assemble = (asmTxt) => {
  const tokens = asmTxt
    .split("\n")
    .filter((v) => !!v.trim() && v[0] !== "*")
    .map(tokenize);

  if (tokens[tokens.length - 2].mn.toLowerCase() !== "end") {
    // If the END instruction is omitted, one is generated by
    // the assembler, and message ASMA140W END record missing is issued
    console.warn("ASMA140W: END record missing");
    // TODO: insert END.
  }

  const expanded = tokens
    .reduce(expandMacros, [])
    .reduce(expandLiterals, { lits: [], stmts: [] });

  // TODO: need to inject literals somewhere - with corresponding PC,
  // _before_ assebmbling the statement.
  console.log("Literals:", expanded.lits);

  const equateExpanded = remapEquates(expanded.stmts);

  const { stmts, symbols, base, base_addr } = equateExpanded
    .map(remapExtendedMnemonics)
    .reduce(assembleStatement, {
      pc: 0,
      stmts: [],
      symbols: {},
      equates: {},
      base: 15, // default to base reg 15. Is that correct?
      base_addr: 0,
    });

  // Some memory for a addressable "graphics screen"
  symbols["screen"] = { pc: 0x100, len: 0x100 };

  const bytes = stmts
    .map((s) => parseOperands(s, symbols, base, base_addr))
    .map(expandDataStatements);

  return {
    stmts,
    bytes,
    symbols,
    addressing: {
      base,
      base_addr,
    },
  };
};

// TODO: naming! stmt=label+op+opers and stmt=stmt+bytes+pc+type

const mk_stmt_toks = (label, mn, operands, comment) => ({
  label,
  mn,
  operands,
  comment,
});

const addStmt = (env, stmt) => {
  const op_code = op_by_mn[stmt.mn.toUpperCase()];
  const op = ops[op_code];
  return env.stmts.push({
    stmt,
    bytes: {
      op_code: [op_code],
      operands: [],
      bytes: [],
    },
    pc: env.pc,
    type: op?.type ?? "??",
  });
};

const addData = (env, stmt) => {
  const d = {
    stmt,
    bytes: {
      op_code: [],
      operands: [],
      bytes: [],
    },
    pc: env.pc,
    type: "DC",
  };
  env.stmts.push(d);
  return d;
};

const tokenizeOperands = (ops) => {
  // comma, followed by NOT open paren, stuff, close paren.
  // Splits on commas, but not inside parens (eg `L R1,0(,R15)`)
  return ops?.split(/,(?![^(]*\))/g) ?? [];
};

const tokenize = (line) => {
  const tok = line.split(" ").reduce((ac, el, i) => {
    if (i === 0 || el !== "") {
      ac.push(el);
    }
    return ac;
  }, []);

  const [label, mn, operands, ...comment] = tok;
  return mk_stmt_toks(
    label.trim(),
    mn,
    tokenizeOperands(operands),
    comment?.join(" ")
  );
};

const parseOperands = (s, symbols, base) => {
  const { stmt, bytes, type } = s;
  // Parse to bytes
  const enc = stmt.operands.map((o, i) =>
    parseOperand(o, symbols, base, type, i, stmt.mn)
  );

  // Re-org operands depending on operation.
  switch (type) {
    case "RR":
    case "RX":
      if (enc.length > 2) {
        console.warn("nop, rong length", enc);
      }
      bytes.operands.push(...enc[0], ...enc[1]);
      break;
    case "RI":
      {
        // extract extra opcode byte
        const extra = ops[bytes.op_code[0]].code[1];
        bytes.operands.push(...enc[0], extra, ...enc[1]);
      }
      break;
    case "SI":
      // I2I2 B1 D1D1D1
      bytes.operands.push(...enc[1], ...enc[0].slice(1));
      break;
    case "SS":
      // L1L1 B1 D1D1D1 B2 D2D2D2
      console.log("eg MVC. TODO!");
      break;
    case "DC":
    case undefined:
      // Just dump the bytes
      enc.forEach((bs) => bytes.operands.push(...bs));
      break;
    default:
      console.log("not rr rx si...", type, enc);
  }
  return s;
};

// Return (mostly?) nibbles
const parseOperand = (o, symbols, base, type, idx, mn) => {
  if (type === "DC") {
    return parseImmediate(o);
  }
  const otype =
    {
      RR: ["R", "R"],
      RX: ["R", "X"],
      SI: ["S", "I"],
      SS: ["I", "X", "X"],
      RI: ["R", "I"],
    }[type] || [];
  const oidx = otype[idx];
  if (type && type !== "DC" && (!otype || !oidx)) {
    console.warn("What's this operand?", type, o, idx, mn);
  }
  switch (oidx) {
    case "R":
      // One number? Correct? Should not be over 15 anyway.
      if (o > 15 || o < 0) console.warn("bad reg", o);
      return parseImmediate(o);
    case "I": {
      const nibs = type === "RI" ? 4 : 2;
      return to_nibs(parseImmediate(o), nibs);
    }
    case "X":
    case "S": {
      return parseBaseDisplace(o, base, symbols);
    }
    default: {
      console.warn("unhandeld mn?", oidx, otype, type);
      return parseImmediate(o);
    }
  }
};

const parseDataOperand = (d) => {
  const numReps = parseInt(d, 10);
  if (isNaN(numReps)) {
    return parseImmediate(d);
  }
  // Expand repetitions
  const value = d.slice((numReps + "").length);
  return new Array(numReps).fill(parseImmediate(value)).flat();
};

const remapExtendedMnemonics = (stmt) => {
  const ext = ops_extended[stmt.mn.toUpperCase()];
  if (ext) {
    stmt.mn = ext.mn;
    stmt.operands = [...ext.operands, ...stmt.operands];
  }
  return stmt;
};

const remapEquates = (stmts) => {
  const eqs = stmts.reduce((ac, el) => {
    const { label, mn, operands } = el;
    if (mn.toLowerCase() === "equ") {
      ac[label.toLowerCase()] = parseImmediate(operands[0])[0] + "";
    }
    return ac;
  }, {});
  return stmts.reduce((ac, el) => {
    if (el.mn.toLowerCase() === "equ") return ac;
    ac.push(el);
    if (el.operands) {
      el.operands = el.operands.map((v) => {
        // Split up base/display parens
        const [first, ...rest] = v.split(/[,()]/g);

        const firstEq = eqs[first.toLowerCase()];
        const head = firstEq !== undefined ? firstEq : first;

        const parens = rest.slice(0, -1).map((v) => {
          const equate = eqs[v.toLocaleLowerCase()];
          return v && equate !== undefined ? equate : v;
        });
        // Rebuild them.
        return head + (parens.length ? "(" + parens.join(",") + ")" : "");
      });
    }
    return ac;
  }, []);
};

const expandMacros = (ac, stmt) => {
  // TODO: expand any macros!
  switch (stmt.mn.toLowerCase()) {
    case "asmdreg":
      {
        console.log("ASMDREG");
        const dcs = [...Array(16)]
          .fill(0)
          .map((_, i) => mk_stmt_toks(`R${i}`, "equ", [i + ""], ""));
        ac.push(...dcs);
      }
      break;
    default:
      ac.push(stmt);
  }
  return ac;
};

const expandLiterals = (ac, stmt) => {
  stmt.operands = stmt.operands.map((o) => {
    if (o.startsWith("=")) {
      const lit = {
        label: "_lit_" + ac.lits.length.toString(),
        value: o.slice(1),
      };
      ac.lits.push(lit);
      return lit.label;
    }
    return o;
  });
  //const value = parseImmediate(o.slice(1));
  //console.log("need to add", o, "to symbols", value, symbols);

  // const mstmt = adddata(env, stmt);
  // const bytes = parsedataoperand(mstmt.stmt.operands[0]);
  // mstmt.stmt.operands = bytes;
  // label && (symbols[label_lc] = { pc: env.pc, len: bytes.length });
  // env.pc += bytes.length;

  //
  ac.stmts.push(stmt);
  return ac;
};

// Ensure data is placed on halfword boundary
const checkBoundaryPadding = (env) => {
  if (env.pc % 4 !== 0) {
    const padding = [0, 0];
    addData(env, mk_stmt_toks("", "DC", padding, ""));
    env.pc += padding.length;
  }
};

const assembleStatement = (env, stmt) => {
  const { symbols } = env;
  const { mn, operands, label } = stmt;
  const label_lc = label.toLowerCase(); // make up...
  const mn_uc = mn.toUpperCase(); // ...your mind

  const op_code = op_by_mn[mn_uc];
  const isData = ["DC", "DS"].includes(mn_uc);
  const isUsing = ["USING"].includes(mn_uc);

  if (op_code) {
    // ====== Regular op code =========

    addStmt(env, stmt);
    label && (symbols[label_lc] = { pc: env.pc, len: ops[op_code].len });
    env.pc += ops[op_code].len;
  } else if (isData) {
    // ======= Data statement: eg `DC 18f'0'` ==========

    checkBoundaryPadding(env);
    const mstmt = addData(env, stmt);
    const bytes = parseDataOperand(mstmt.stmt.operands[0]);
    mstmt.stmt.operands = bytes;
    label && (symbols[label_lc] = { pc: env.pc, len: bytes.length });
    env.pc += bytes.length;
  } else if (isUsing) {
    // ========= USING statement ============

    const [addr, base] = operands;
    const addr_lc = addr.trim().toLowerCase();
    env.base = parseInt(base, 10);
    // TODO: currently only finds symbols _before_ current statement!
    env.base_addr = addr_lc === "*" ? env.pc : symbols[addr_lc];
  } else {
    // ============= Label ============

    const lbltxt = label ? `[${label}]` : " ";
    label && (symbols[label_lc] = { pc: env.pc, len: 4 });
    console.log("miss:", mn, (operands ?? [" "]).join(","), lbltxt);
  }

  return env;
};

const parseImmediate = (v) => {
  const [a, b, ...rest] = v.toString().split("");
  if (b === "'") {
    const num = rest.slice(0, -1).join("");
    switch (a.toLowerCase()) {
      case "b":
        return [parseInt(num, 2)];
      case "x":
        return [parseInt(num, 16)];
      case "c":
        return [eb2code(rest[0])];
      case "f":
        return fw_to_bytes(parseInt(num, 10));

      default:
        console.log("Other parse immediate:", a, num);
        return [parseInt(num, 10)];
    }
  } else {
    switch (a) {
      case "f":
        return [];
    }
  }

  return [parseInt(v, 10)];
};

// SYmbol definition:
/*
  The symbol must not consist of more than 63 alphanumeric characters.
  The first character must be an alphabetic character.
  An alphabetic character is a letter from A through Z,
  or from a through z, or $, _, #, or @.
  The other characters in the symbol can be alphabetic characters,
  digits, or a combination of the two.

  The assembler does not distinguish between upper-case and lower-case letters used in symbols.
*/

const parseBaseDisplace = (o, base, symbols) => {
  const INDEX = 0;
  const bdregex = /([\d\w]+)\(([\d\w]*),([\d\w]+)\)/g;
  const matches = [...o.matchAll(bdregex)].flat();

  if (matches.length === 4) {
    //base disp
    const [, disp, index, base] = matches;
    const mindex = parseInt(index, 10) || 0;
    const mbase = parseInt(base, 10) || 0;
    const mdisp = parseInt(disp, 10) || 0;
    return [mindex, mbase, ...to_nibs(mdisp, 3)];
  } else if (symbols[o.toLowerCase()]) {
    return [INDEX, base, ...disp_to_nibs(symbols[o.toLowerCase()].pc)];
  } else {
    console.warn("Missing symbol:", o);
  }
  return [INDEX, base, 0, 0, 0];
};

const expandDataStatements = (s) => {
  if (s.stmt.mn.toUpperCase() === "DC") {
    s.bytes.bytes = [...s.bytes.operands];
  } else {
    s.bytes.bytes = [
      ...s.bytes.op_code,
      ...chunk(s.bytes.operands.flat(), 2).map((b) => byte_from(...b)),
    ];
  }
  return s;
};
